pipeline {
    agent {
        label 'build-agent'
    }

    environment {
        S3_BUCKET = "med-erp-frontend"
        AWS_REGION = "us-east-1"
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Deploy to S3') {
            steps {
                sh 'aws s3 sync dist/ s3://${S3_BUCKET} --region ${AWS_REGION}'
            }
        }
    }
}
