pipeline {
    agent {
        label 'build-agent'
    }

    environment {
        AWS_REGION = "us-east-1"
        ECR_REGISTRY = "261945560801.dkr.ecr.us-east-1.amazonaws.com"
        ECR_REPO = "med-erp/product-service"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('mvn build') {
            steps {
                dir('product-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('product-service') {
                    sh 'docker build -t ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                sh 'aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}'
                sh 'docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}'
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                    aws eks update-kubeconfig --region ${AWS_REGION} --name ${CLUSTER_NAME}

                    kubectl apply -f k8s/product-service.yaml -n med-erp

                    kubectl set image deployment/product-service product-service=${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} -n med-erp

                    kubectl rollout status deployment/product-service -n med-erp
                '''
            }
        }
    
    }
}