pipeline {
    agent {
        label 'build-agent'
    }

    environment {
        AWS_REGION = "us-east-1"
        ECR_REGISTRY = "261945560801.dkr.ecr.us-east-1.amazonaws.com"
        ECR_REPO = "med-erp/order-service"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('mvn build') {
            steps {
                dir('order-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
               dir('order-service') {
                    sh 'docker build -t ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                sh 'aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}'
                sh 'docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}'
            }
        }
    
    }
}