apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: med-erp

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: 261945560801.dkr.ecr.us-east-1.amazonaws.com/med-erp/product-service:latest
          ports:
            - containerPort: 8082
          
          envFrom:
            - secretRef:
                name: product-service
          
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"  
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: med-erp
  
spec:
  selector:
    app: product-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: product-service
  namespace: med-erp

type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://mongodbuser:mongodb%408087@mederpdb.gxofhva.mongodb.net/products_db?appName=mederpdb
  JWT_SECRET: 7f3c9a2e1b6d4f8a9c0e3b7d5a1f6c82e4d9b3a7c1f5e8d2
  CORS_ALLOWED_ORIGINS: http://localhost:5173,https://prafulgadbail.online
  LOW_STOCK_THRESHOLD: 10
